### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by nikunjdk** [nikunjdk/Bizzare-Buzz#3]
Needs UI/UX improvement. Unleash your creativity and you can do anything you want as long as it doesn't change the basic features. You can even change background images, colours, fonts etc if you want. Also, I will be accepting multiple pull requests on this issue so I won't be assigning it to a particular person. Please add a screenshot of the page whenever you make a pr.

UPDATE: I will no longer be accepting prs for changes in the first page (Unless it is really good). So try to make some changes in the second-page guys.

**Comment by Kapilshanbhag09** [comment]
I can give a try.

**Comment by nikunjdk** [comment]
> I can give a try.

Sure, Go ahead!

**Comment by teyim** [comment]
can i work on this?

**Comment by nikunjdk** [comment]
> can i work on this?

Yes you can

**Comment by hvirmani** [comment]
can i work

**Comment by nikunjdk** [comment]
> can i work

Sure

**Comment by Kapilshanbhag09** [comment]
I have added some changes in home page.
![image](https://user-images.githubusercontent.com/56125734/94736332-b19a1480-0389-11eb-85a9-8c5a8d47ead1.png)
![image](https://user-images.githubusercontent.com/56125734/94736348-b959b900-0389-11eb-93c9-6ea5c642ea66.png)

**Comment by climbingryan** [comment]
Can i work on this? Wanna see what i can add in.
Also my first time participating in hacktoberfest.

**Comment by fawadkhan97** [comment]
should I update your table to this? will you accept my PR?


[https://snipboard.io/7jzTeZ.jpg](url)

![tablepng](https://user-images.githubusercontent.com/52420711/95676664-20247100-0bd9-11eb-962c-d84b11e41516.png)

**Comment by nikunjdk** [comment]
No, This issue is closed now.
